### ISSUE TITLE
Valid pull request rejected. Is the project still active?

### ISSUE THREAD

**Issue by aishelm** [ctstone/csredis#32]
Hi Chris:

I encountered an issue with the RedisSentinelManager, in which the host being saved included the port number. I also saw there is already a pull request for this fix, along with 2 other pull request. All the three pull request are marked as failed because of the same issue "Cryptographic failure while signing assembly".
I further realized the version labeled in the github project doesn't correspond with the latest version in the nuget.org site: the last label I see in the cloned repo is v 3.2.1.
Is the project still maintained, or am I missing something?
Thanks a lot.

**Comment by ctstone** [comment]
@aishelm I have unfortunately not had time to review the outstanding pull requests. As you noted, the versioning is out of sync between nuget and github, and that is something I should probably resolve first to make sure streams don't get crossed.

The signing error must be something to do with the automatic StrongName signing that I'm using on AppVeyor. Maybe it only works properly when I initiate a build from my account.

The host fix sounds pretty easy though. I will try to merge that into the latest release.

**Comment by aishelm** [comment]
Thanks for the prompt clarification. I know we are all always busy. 
Please let me know if i can be of any help.
